export interface CategoryKeywords {
  cat: string;
  keywords: string[];
}

export const CATEGORY_KEYWORDS: CategoryKeywords[] = [
  {
    cat: "food",
    keywords: [
      "restaurant",
      "groceries",
      "meal",
      "snack",
      "beverage",
      "coffee",
      "dessert",
      "takeout",
      "delivery",
      "catering",
      "street food",
      "hut",
      "pizza",
      "sushi",
      "ramen",
      "pho",
      "tacos",
      "burger",
      "hot dog",
      "fries",
      "chicken",
      "noodles",
      "rice",
      "stir-fry",
      "fried",
      "dumplings",
      "falafel",
      "wrap",
      "kebab",
      "gyro",
      "shawarma",
      "pasta",
      "seafood",
      "poke",
      "sandwich",
      "bagel",
      "croissant",
      "pancake",
      "waffle",
      "ice",
      "cream",
      "baklava",
      "pad thai",
      "restaurant",
      "groceries",
      "meal",
      "snack",
      "beverage",
      "coffee",
      "fries",
      "chicken",
      "noodles",
      "rice",
      "stir-fry",
      "pasta",
      "ice cream",
      "baklava",
      "pad thai",
      "curry",
      "roti",
      "rotti",
      "naan",
      "tandoori",
      "biryani",
      "masala",
      "dal",
      "paneer",
      "chana",
      "saag",
      "chutney",
      "samosa",
      "papadum",
      "lassi",
      "chai",
      "dosa",
      "idli",
      "paratha",
      "parata",
      "porridge",
      "tikka",
      "korma",
      "vindaloo",
      "butter",
      "chicken",
      "bowl",
      "smoothie",
      "burrito",
      "taco",
      "enchilada",
      "quesadilla",
      "tortilla",
      "chips",
      "salsa",
      "guacamole",
      "margarita",
      "mole",
      "churro",
      "tostada",
      "tamale",
      "empanada",
      "arepa",
      "patacon",
      "pabellon",
      "ceviche",
      "bandeja paisa",
      "aji",
      "pisco",
      "sangria",
      "paella",
      "tapas",
      "gazpacho",
      "tortilla",
      "gambas",
      "patatas",
      "croqueta",
      "churro",
      "flan",
      "churros",
      "chocolate",
      "beer",
      "sangria",
      "sambol",
      "juice",
      "kiribath",
      "milk",
      "breakfast",
      "lunch",
      "dinner",
      "brunch",
      "buffet",
      "dining",
      "cuisine",
      "plates",
      "cafe",
      "coffee",
      "bar",
      "pub",
      "bistro",
      "diner",
      "bakery",
      "deli",
      "food",
      "truck",
      "food",
      "court",
      "hall",
      "market",
      "stall",
      "stand",
      "cart",
      "vendor",
      "Restaurant",
      "Lebensmittel",
      "Mahlzeit",
      "Snack",
      "Getränk",
      "Kaffee",
      "Kneipe",
      "Imbiss",
      "Bäckerei",
      "Delikatessen",
      "Essen",
      "Nachtisch",
      "Markt",
      "alimentation",
      "repas",
      "collation",
      "boisson",
      "café",
      "bar",
      "cassecroûte",
      "boulangerie",
      "traiteur",
      "nourriture",
      "marché",
    ],
  },
  {
    cat: "international-travel",
    keywords: [
      "flight",
      "plane",
      "airline",
      "airport",
      "airfare",
      "ticket",
      "boat",
      "cruise",
      "visa",
      "passport",
      "tour",
      "language",
      "culture",
      "currency",
      "souvenir",
      "international",
      "duty-free",
      "currency exchange",
      "travel insurance",
      "baggage fees",
      "overseas",
      "language translator",
      "power adapter",
      "travel pillow",
      "earplugs",
      "eye mask",
      "compression socks",
      "neck pillow",
      "Flug",
      "Flugzeug",
      "Fluggesellschaft",
      "Flughafen",
      "Flugpreis",
      "Ticket",
      "Boot",
      "Kreuzfahrt",
      "Visum",
      "Reisepass",
      "Tour",
      "Sprache",
      "Kultur",
      "Währung",
      "Souvenir",
      "international",
      "zollfrei",
      "Währungsumtausch",
      "Reiseversicherung",
      "Gepäckgebühren",
      "Übersee",
      "Sprachübersetzer",
      "Netzadapter",
      "Reisekissen",
      "Ohrstöpsel",
      "Augenmaske",
      "Kompressionsstrümpfe",
      "Nackenkissen",
      "vol",
      "avion",
      "compagnie aérienne",
      "aéroport",
      "tarif aérien",
      "billet",
      "bateau",
      "croisière",
      "visa",
      "passeport",
      "tour",
      "langue",
      "culture",
      "devise",
      "souvenir",
      "international",
      "duty-free",
      "change de devises",
      "assurance voyage",
      "frais de bagages",
      "outre-mer",
      "traducteur de langue",
      "adaptateur secteur",
      "oreiller de voyage",
      "bouchons d'oreilles",
      "masque pour les yeux",
      "chaussettes de compression",
      "oreiller cervical",
    ],
  },
  {
    cat: "accomodation",
    keywords: [
      "hotel",
      "hostel",
      "motel",
      "resort",
      "bed & breakfast",
      "apartment",
      "room",
      "lodging",
      "reservation",
      "amenity",
      "hotel",
      "motel",
      "hostel",
      "guesthouse",
      "airbnb",
      "resort",
      "camping",
      "glamping",
      "vacation",
      "apartment",
      "cabin",
      "villa",
      "boutique",
      "bed and breakfast",
      "bnb",
      "luxury",
      "budget",
      "pet-friendly",
      "family-friendly",
      "room service",
      "housekeeping",
      "laundry",
      "free wifi",
      "swimming pool",
      "concierge",
      "airport shuttle",
      "parking",
      "breakfast included",
      "hôtel",
      "auberge",
      "motel",
      "resort",
      "chambre d'hôtes",
      "appartement",
      "chambre",
      "hébergement",
      "réservation",
      "commodité",
      "hôtel",
      "motel",
      "auberge",
      "guesthouse",
      "airbnb",
      "resort",
      "camping",
      "glamping",
      "vacances",
      "appartement",
      "cabine",
      "villa",
      "boutique",
      "bed and breakfast",
      "bnb",
      "luxe",
      "budget",
      "pet-friendly",
      "familial",
      "room service",
      "housekeeping",
      "blanchisserie",
      "wifi gratuit",
      "piscine",
      "concierge",
      "navette aéroport",
      "parking",
      "petit déjeuner inclus",
      "Herberge",
      "Motel",
      "Ferienanlage",
      "Bed & Breakfast",
      "Wohnung",
      "Zimmer",
      "Beherbergung",
      "Reservierung",
      "Annehmlichkeit",
      "Hotel",
      "Motel",
      "Herberge",
      "Gästehaus",
      "airbnb",
      "Ferienanlage",
      "Camping",
      "Glamping",
      "Urlaub",
      "Wohnung",
      "Hütte",
      "Villa",
      "Boutique",
      "Übernachtung mit Frühstück",
      "bnb",
      "Luxus",
      "Budget",
      "haustierfreundlich",
      "familienfreundlich",
      "Zimmerservice",
      "Hauswirtschaft",
      "Wäscherei",
      "kostenloses WLAN",
      "Schwimmbad",
      "Concierge",
      "Flughafen-Shuttle",
      "Parken",
      "Frühstück inklusive",
    ],
  },
  {
    cat: "national-travel",
    keywords: [
      "rental",
      "train",
      "bus",
      "road",
      "trip",
      "fuel",
      "parking",
      "toll",
      "route",
      "vehicle",
      "transportation",
      "gas",
      "tolls",
      "public",
      "car",
      "bike",
      "scooter",
      "taxi",
      "ride",
      "share",
      "hiking",
      "guidebook",
      "maps",
      [
        "Vermietung",
        "Zug",
        "Bus",
        "Straße",
        "Reise",
        "Kraftstoff",
        "Parken",
        "Maut",
        "Strecke",
        "Fahrzeug",
        "Transport",
        "Gas",
        "Maut",
        "öffentlich",
        "Auto",
        "Fahrrad",
        "Motorroller",
        "Taxi",
        "Fahrt",
        "teilen",
        "Wandern",
        "Reiseführer",
        "Karten",
        "location",
        "train",
        "bus",
        "route",
        "voyage",
        "carburant",
        "parking",
        "péage",
        "route",
        "véhicule",
        "transport",
        "gaz",
        "péage",
        "public",
        "voiture",
        "vélo",
        "scooter",
        "taxi",
        "ride",
        "partager",
        "randonnée",
        "guide",
        "cartes",
      ],
    ],
  },
  {
    cat: "other",
    keywords: [
      "miscellaneous",
      "bill",
      "fee",
      "subscription",
      "entertainment",
      "shopping",
      "groceries",
      "health",
      "education",
      "personal",
      "care",
      "mobile",
      "phone",
      "plan",
      "internet service",
      "utilities",
      "rent",
      "mortgage",
      "home",
      "health",
      "life",
      "insurance",
      "pet expenses",
      "childcare",
      "school",
      "tuition",
      "books",
      "supplies",
      "subscriptions",
      "memberships",
      "gym membership",
      "streaming services",
      "e-books",
      "audiobooks",
      "podcast",
      "personal",
      "grooming",
      "clothing",
      "shoes",
      "accessories",
      "gifts",
      "donations",
      "taxes",
      "investment",
      "bank",
      "fees",
      "Toiletries",
      "Sunscreen",
      "Insect repellent",
      "First aid kit",
      "Bandages",
      "Pain relievers",
      "Cold medicine",
      "Allergy medicine",
      "Contact lens solution",
      "Glasses cleaner",
      "Hand sanitizer",
      "Tissues",
      "Wet wipes",
      "Batteries",
      "Flashlight",
      "Umbrella",
      "Rain poncho",
      "Travel pillow",
      "Ear plugs",
      "Eye mask",
      "Notebook",
      "Pens",
      "Map",
      "Guidebook",
      "Phrasebook",
      "Travel adapter",
      "Charging cables",
      "Earbuds",
      "Portable charger",
      "Camera",
      "Memory card",
      "Books",
      "Magazines",
      "Playing cards",
      "Gifts",
      "Postcards",
      "Souvenirs",
      "Clothing",
      "Shoes",
      "Hats",
      "Sunglasses",
      "Jewelry",
      "Scarves",
      "Gloves",
      "Wallet",
      "Passport holder",
      "Luggage tags",
      "Lock",
      "Laundry detergent",
      "Ziploc bags",
      "tampons",
      "divers",
      "facture",
      "frais",
      "abonnement",
      "divertissement",
      "achats",
      "épicerie",
      "santé",
      "éducation",
      "personnel",
      "soins",
      "mobile",
      "téléphone",
      "plan",
      "service",
      "services publics",
      "loyer",
      "hypothèque",
      "maison",
      "santé",
      "vie",
      "assurance",
      "compagnie",
      "garde d'enfants",
      "école",
      "frais de scolarité",
      "livres",
      "fournitures",
      "abonnements",
      "adhésions",
      "abonnement",
      "stream",
      "livre",
      "audio",
      "podcast",
      "personnel",
      "toilettage",
      "vêtements",
      "chaussures",
      "accessoires",
      "cadeaux",
      "dons",
      "taxes",
      "investissement",
      "banque",
      "frais",
      "toilette",
      "crème",
      "Répulsif",
      "Trousse",
      "Bandages",
      "Analgésiques",
      "Médicaments",
      "Solution",
      "lentilles de contact",
      "Nettoyant",
      "Désinfectant",
      "Mouchoirs",
      "Lingettes",
      "Piles",
      "Lampe",
      "Parapluie",
      "poncho",
      "voyage",
      "Oreill",
      "Bouchons",
      "Masque",
      "Carnet",
      "Stylos",
      "Carte",
      "Guide",
      "Phrasebook",
      "Adaptateur",
      "Câble",
      "Ecouteurs",
      "Chargeur",
      "photo",
      "mémoire",
      "Livres",
      "Magazines",
      "jouer",
      "Cadeaux",
      "Cartes",
      "Souvenirs",
      "Vêtements",
      "Chaussures",
      "Chapeaux",
      "Lunettes",
      "Bijoux",
      "Foulards",
      "Gants",
      "Portefeuille",
      "Porte-passeport",
      "Etiquettes",
      "Serrure",
      "Détergent",
      "Sacs Ziploc",
      "tampons",
      "Verschiedenes",
      "Rechnung",
      "Gebühr",
      "Abonnement",
      "Unterhaltung",
      "Einkaufen",
      "Lebensmittel",
      "Gesundheit",
      "Bildung",
      "Persönlich",
      "Pflege",
      "mobil",
      "Telefon",
      "Plan",
      "Internet",
      "Miete",
      "Hypothek",
      "Zuhause",
      "Gesundheit",
      "Leben",
      "Versicherung",
      "Haustiere",
      "Kinderbetreuung",
      "Schule",
      "Schulgeld",
      "Bücher",
      "Zubehör",
      "Abonnements",
      "Mitglied",
      "Fitnes",
      "Streaming-Dienste",
      "E-Bücher",
      "Hörbücher",
      "Podcast",
      "persönlich",
      "Körperpflege",
      "Kleidung",
      "Schuhe",
      "Zubehör",
      "Geschenke",
      "Spenden",
      "Steuern",
      "Investition",
      "Bank",
      "Gebühren",
      "Toilettenartikel",
      "Sonnenschutz",
      "Insektenschutz",
      "Erste-Hilfe-Kasten",
      "Verbände",
      "Schmerz",
      "Erkältung",
      "Allergie",
      "Kontaktlinsen",
      "Brillenreiniger",
      "desinfektion",
      "Taschentücher",
      "Feuchttücher",
      "Batterien",
      "Taschenlampe",
      "Regenschirm",
      "Regenponcho",
      "Reisekopfkissen",
      "Ohrstöpsel",
      "Augenmaske",
      "Notizbuch",
      "Stifte",
      "Karte",
      "Reiseführer",
      "Sprachführer",
      "Reiseadapter",
      "Ladekabel",
      "Ohrstöpsel",
      "Tragbares Ladegerät",
      "Kamera",
      "Speicherkarte",
      "Bücher",
      "Zeitschriften",
      "Spielkarten",
      "Geschenke",
      "Postkarten",
      "Souvenirs",
      "Kleidung",
      "Schuhe",
      "Hüte",
      "Sonnenbrillen",
      "Schmuck",
      "Schals",
      "Handschuhe",
      "Brieftasche",
      "Reisepasshalter",
      "Gepäckanhänger",
      "Schloss",
      "Waschmittel",
      "Ziploc",
      "Beutel",
      "Tampons",
    ],
  },
];
