import axios from "axios";

export function storeExpense(expenseData) {
  axios.post(
    // firebase wants to have a .json ending (/expenses folder)
    "https://travelcostnative-default-rtdb.asia-southeast1.firebasedatabase.app/expenses.json",
    // id will be autogenerated
    expenseData
  );
}
